#!/bin/bash
### Global variables for Submariner setup and tests ###

export GOROOT="/usr/local/go"
export PATH="${GOROOT}/bin:${PATH}"
export GOBIN="${GOROOT}/bin"

export WORKDIR=~/submariner-install
export OC="${GOBIN}/oc"
export OCPUP_DIR="${WORKDIR}/ocpup"
export MERGED_KUBCONF="${WORKDIR}/merged_kubeconfig"

# TODO: Change the cluster of Broker to be different than cluster A
export BROKER_CLUSTER_NAME="cluster-a"
export KUBECONF_BROKER=${WORKDIR}/${BROKER_CLUSTER_NAME}/auth/kubeconfig
export BROKER_INFO="broker-info.subm"
export SUBM_NAMESPACE="submariner-operator"

export CLUSTER_A_NAME="cluster-a"
export CLUSTER_A_DIR=${WORKDIR}/${CLUSTER_A_NAME}
export KUBECONF_CLUSTER_A=${CLUSTER_A_DIR}/auth/kubeconfig
export CLUSTER_A_YAML="${CLUSTER_A_YAML:-${WORKDIR}/setup-cluster-a.yaml}"
export NETSHOOT_CLUSTER_A="netshoot-cl-a"

export CLUSTER_B_NAME="cluster-b"
export CLUSTER_B_DIR=${OCPUP_DIR}/.config/cl1
export KUBECONF_CLUSTER_B=${CLUSTER_B_DIR}/auth/kubeconfig
export CLUSTER_B_YAML="${CLUSTER_B_YAML:-${WORKDIR}/setup-cluster-b.yaml}"
export NGINX_CLUSTER_B="nginx-cl-b"

export AWS_KEY="user-aws-access-key"
export AWS_SECRET="user-aws-secret-access-key"
export AWS_PROFILE_NAME="aws-profile"
export AWS_PROFILE_ID="012345678910"
export AWS_REGION="aws-region"
export AWS_ZONE_NAME="aws-zone-name"
export AWS_ZONE_ID="aws-zone-id"

export AWS_DNS_ALIAS1="api.${CLUSTER_A_NAME}.${AWS_ZONE_NAME}."
export AWS_DNS_ALIAS2="\052.apps.${CLUSTER_A_NAME}.${AWS_ZONE_NAME}."

export BROKER_NATPORT=4500
export BROKER_IKEPORT=500

export SUBM_TEST_NS="${SUBM_TEST_NS:-test-submariner}"

export REPORT_NAME="${REPORT_NAME:-Submariner Tests}"
