#!/bin/bash
### Global variables for Submariner setup and tests ###
#
# To override variable with an existing environment variable from active session:
# Change variable assignment format from VAR="value" to VAR="${VAR:-value}"

export WORKDIR=~/submariner-install

export GOROOT="/usr/local/go"
export PATH="${GOROOT}/bin:${PATH}"
export GOBIN="${WORKDIR}/GOBIN" # or "${GOROOT}/bin" if using system's default golnag

export OC="${GOBIN}/oc"
export OCPUP_DIR="${WORKDIR}/ocpup"

# TODO: Change the cluster of Broker to be different than cluster A
export BROKER_CLUSTER_NAME="cluster-a"
# export KUBECONF_BROKER=${WORKDIR}/${BROKER_CLUSTER_NAME}/auth/kubeconfig
export BROKER_INFO="broker-info.subm"
export BROKER_NAMESPACE="submariner-k8s-broker"
export SUBM_NAMESPACE="submariner-operator"

export CLUSTER_A_NAME="cluster-a"
# export CLUSTER_A_DIR=${WORKDIR}/${CLUSTER_A_NAME}
# export KUBECONF_CLUSTER_A=${CLUSTER_A_DIR}/auth/kubeconfig
export CLUSTER_A_YAML="${CLUSTER_A_YAML:-${WORKDIR}/setup-cluster-a.yaml}"
export NETSHOOT_CLUSTER_A="netshoot-cl-a"

export CLUSTER_B_NAME="cluster-b"
# export CLUSTER_B_DIR=${OCPUP_DIR}/.config/cl1
# export KUBECONF_CLUSTER_B=${CLUSTER_B_DIR}/auth/kubeconfig
export CLUSTER_B_YAML="${CLUSTER_B_YAML:-${WORKDIR}/setup-cluster-b.yaml}"
export NGINX_CLUSTER_B="nginx-cl-b"

export AWS_KEY="user-aws-access-key"
export AWS_SECRET="user-aws-secret-access-key"
export AWS_PROFILE_NAME="aws-profile"
export AWS_PROFILE_ID="012345678910"
export AWS_REGION="aws-region"
export AWS_ZONE_NAME="aws-zone-name"
export AWS_ZONE_ID="aws-zone-id"

export AWS_DNS_ALIAS1="api.${CLUSTER_A_NAME}.${AWS_ZONE_NAME}."
export AWS_DNS_ALIAS2="\052.apps.${CLUSTER_A_NAME}.${AWS_ZONE_NAME}."

export IPSEC_NATT_PORT=${IPSEC_NATT_PORT:-4501}
export IPSEC_IKE_PORT=${IPSEC_IKE_PORT:-501}
export GW_INSTANCE_TYPE=${GW_INSTANCE_TYPE:-m4.xlarge}

export MULTI_CLUSTER_DOMAIN="clusterset.local"

export TEST_NS="${TEST_NS:-test-submariner}"
export REPORT_NAME="${REPORT_NAME:-Submariner Tests}"

export POLARION_SERVER="polarion.server.name" # without " https:// "
export POLARION_USR="polarion-user"
export POLARION_PWD='polarion-pass' # in single quotes
export POLARION_PROJECT_ID="${POLARION_PROJECT_ID:-}"
export POLARION_TEAM_NAME="${POLARION_TEAM_NAME:-}"
export POLARION_TESTRUN_TEMPLATE="${POLARION_TESTRUN_TEMPLATE:-}"
